### ISSUE TITLE
"Can not read property 3 of null" error

### ISSUE THREAD

**Issue by ceremcem** [stephenhutchings/jade-static-brunch#2]
If any file is present with `.jade` extension in `app/` except for `app/static/`, this error is thrown. 

config: 

``` coffee
exports.config =
  # See http://brunch.readthedocs.org/en/latest/config.html for documentation.
  files:
    javascripts:
      joinTo:
        'javascripts/app.js': /^app/
        'javascripts/vendor.js': /^vendor/
        'test/javascripts/test.js': /^test(\/|\\)(?!vendor)/
        'test/javascripts/test-vendor.js': /^test(\/|\\)(?=vendor)/
      order:
        # Files in `vendor` directories are compiled before other files
        # even if they aren't specified in order.before.
        before: [
          'vendor/scripts/jquery-1.11.js',
          'vendor/flot.min/jquery.flot.min.js'
        ]

    stylesheets:
      joinTo:
        'stylesheets/app.css': /^(app|vendor)/
        'test/stylesheets/test.css': /^test/
      order: {}
      #after: ['app/styles/aktos-dcs-partial-styles.css']

  plugins:
    jadeStatic:
      locals: {}                    # Locals passed to the template
      formatPath: (path) -> path.match(/^app(\/|\\)static(\/|\\)(.+)\.jade$/)[3]
      extension: '.html'            # Extension of compiled templates
      pretty: true                  # Any other Jade API option
```

**Comment by stephenhutchings** [comment]
The `formatPath` function in the README is just an example, and should be changed to match whatever project structure you have chosen. Here it's trying to match any path inside `app/static/your/path` and will compile it to `your/path` instead.

**Comment by ceremcem** [comment]
Thanks for the reply. I couldn't find a documentation `formatPath` variable. I looked in the source code, I couldn't figure out either.

Here is my attempt to understand what this function does: 

```
  plugins:
    jadeStatic:
      #compileDebug: true
      locals: {}                    # Locals passed to the template
      formatPath: (path) -> 
        console.log "path is: ", path
        try
          path.match(/^app(\/|\\)static(\/|\\)(.+)\.jade$/)[3]
      extension: '.html'            # Extension of compiled templates
      pretty: true                  # Any other Jade API option
```

Now everything is compiled successfully, event there is a `app/test.jade` file present: 

```
$ brunch build
path is:  app/test.jade
path is:  app/static/brunch.jade
path is:  app/static/mixins.jade
path is:  app/static/mypage.jade
path is:  app/static/ractive.jade
24 Aug 11:05:27 - info: compiled 47 files into 4 files, copied 1379 in 2571ms
```

But again, I needed to close all opened files: https://github.com/stephenhutchings/jade-static-brunch/issues/4
